# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2242566c-7cef-488f-a861-76dbb578261d";
      fsType = "btrfs";
      options = [ "compress=lzo" "noatime" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2242566c-7cef-488f-a861-76dbb578261d";
      fsType = "btrfs";
      options = [ "compress=lzo" "noatime" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2242566c-7cef-488f-a861-76dbb578261d";
      fsType = "btrfs";
      options = [ "compress=lzo" "noatime" "subvol=nix" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/2242566c-7cef-488f-a861-76dbb578261d";
      fsType = "btrfs";
      options = [ "noatime" "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2FA7-65AB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 8*1024; # Creates an 8GB swap file
  }];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
